<?php

/**
 * Voluntario filter form base class.
 *
 * @package    voluntarios
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseVoluntarioFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'deleted_at'                        => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'nombre'                            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'primer_apellido'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'segundo_apellido'                  => new sfWidgetFormFilterInput(),
      'tipo_documento_identificativo'     => new sfWidgetFormChoice(array('choices' => array('' => '', 'NIF' => 'NIF', 'Pasaporte' => 'Pasaporte', 'NIE' => 'NIE', 'Otro documento' => 'Otro documento'))),
      'numero_documento_identificativo'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'sexo'                              => new sfWidgetFormChoice(array('choices' => array('' => '', 'Masculino' => 'Masculino', 'Femenino' => 'Femenino'))),
      'talla'                             => new sfWidgetFormChoice(array('choices' => array('' => '', 'S' => 'S', 'M' => 'M', 'L' => 'L', 'XL' => 'XL', 'XXL' => 'XXL', 'XXXL' => 'XXXL'))),
      'nacionalidad'                      => new sfWidgetFormFilterInput(),
      'fecha_nacimiento'                  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'pais'                              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'provincia_id'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Provincia'), 'add_empty' => true)),
      'codigo_postal'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ciudad'                            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipo_via'                          => new sfWidgetFormFilterInput(),
      'direccion'                         => new sfWidgetFormFilterInput(),
      'numero_via'                        => new sfWidgetFormFilterInput(),
      'escalera'                          => new sfWidgetFormFilterInput(),
      'piso'                              => new sfWidgetFormFilterInput(),
      'puerta'                            => new sfWidgetFormFilterInput(),
      'telefono_fijo'                     => new sfWidgetFormFilterInput(),
      'telefono_movil'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fax'                               => new sfWidgetFormFilterInput(),
      'email'                             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nivel_estudios'                    => new sfWidgetFormChoice(array('choices' => array('' => '', 'Sin estudios' => 'Sin estudios', 'Estudios básicos' => 'Estudios básicos', 'Bachillerato' => 'Bachillerato', 'Formación profesional' => 'Formación profesional', 'Diplomatura o Ingeniería Técnica' => 'Diplomatura o Ingeniería Técnica', 'Licenciatura o Ingeniería Superior' => 'Licenciatura o Ingeniería Superior'))),
      'especialidad'                      => new sfWidgetFormFilterInput(),
      'otros_estudios'                    => new sfWidgetFormFilterInput(),
      'nivel_ingles'                      => new sfWidgetFormChoice(array('choices' => array('' => '', 'No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'nivel_frances'                     => new sfWidgetFormChoice(array('choices' => array('' => '', 'No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'nivel_aleman'                      => new sfWidgetFormChoice(array('choices' => array('' => '', 'No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'otro_idioma'                       => new sfWidgetFormFilterInput(),
      'nivel_otro_idioma'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'experiencia_administracion'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_turismo'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_informatica'           => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_seguridad'             => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_educacion'             => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_sanitario'             => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_traduccion'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_recursos_humanos'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_otro'                  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_otro_campo'            => new sfWidgetFormFilterInput(),
      'experiencia_voluntario'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'experiencia_voluntario_donde'      => new sfWidgetFormFilterInput(),
      'experiencia_trato_discapacitados'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'carnet_conducir'                   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'parroquia_id'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Parroquia'), 'add_empty' => true)),
      'compromiso_religioso'              => new sfWidgetFormChoice(array('choices' => array('' => '', 'Básico' => 'Básico', 'Laico comprometido' => 'Laico comprometido', 'Catequista' => 'Catequista', 'Ministro de la comunión' => 'Ministro de la comunión'))),
      'movimiento_id'                     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Movimiento'), 'add_empty' => true)),
      'disponibilidad_dias'               => new sfWidgetFormChoice(array('choices' => array('' => '', 'Fines de semana' => 'Fines de semana', 'De lunes a viernes' => 'De lunes a viernes', 'Toda la semana' => 'Toda la semana'))),
      'disponibilidad_horas'              => new sfWidgetFormChoice(array('choices' => array('' => '', 'Mañana' => 'Mañana', 'Tarde' => 'Tarde', 'Indiferente' => 'Indiferente'))),
      'colaborar_acogida'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'colaborar_viacrucis'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'colaborar_vigilia'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'colaborar_despedida'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'colaborar_ambientacion'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'colaborar_protocolo'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'colaborar_ministro_comunion'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'autorizacion_boletin'              => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'autorizacion_diocesis'             => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'aceptacion_condiciones'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'alojamiento'                       => new sfWidgetFormChoice(array('choices' => array('' => '', 'Domicilio personal' => 'Domicilio personal', 'IFEMA' => 'IFEMA', 'Polideportivo' => 'Polideportivo', 'Albergue' => 'Albergue', 'Otro domicilio' => 'Otro domicilio'))),
      'apto'                              => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'revisado_policia'                  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'jefe_equipo'                       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'notas'                             => new sfWidgetFormFilterInput(),
      'reunion_inicial'                   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'equipo_id'                         => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Equipo'), 'add_empty' => true)),
      'foto'                              => new sfWidgetFormFilterInput(),
      'pagado'                            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'entrevista_seleccion'              => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'abono_transporte'                  => new sfWidgetFormChoice(array('choices' => array('' => '', 'Primera y segunda semana' => 'Primera y segunda semana', 'Sólo segunda semana' => 'Sólo segunda semana'))),
      'numero_acreditacion'               => new sfWidgetFormFilterInput(),
      'registrado'                        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'documento_identificacion_personal' => new sfWidgetFormFilterInput(),
      'documento_acreditacion'            => new sfWidgetFormFilterInput(),
      'documento_compromiso'              => new sfWidgetFormFilterInput(),
      'documento_antecedentes_penales'    => new sfWidgetFormFilterInput(),
      'documento_autorizacion_paterna'    => new sfWidgetFormFilterInput(),
      'medio_transporte'                  => new sfWidgetFormChoice(array('choices' => array('' => '', 'Ninguno' => 'Ninguno', 'Avión' => 'Avión', 'Tren' => 'Tren', 'Autobús' => 'Autobús', 'Coche' => 'Coche'))),
      'fecha_llegada'                     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'fecha_salida'                      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'datos_transporte'                  => new sfWidgetFormFilterInput(),
      'nivel_seguridad_1'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_2'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_3'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_4'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_5'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_6'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_7'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_8'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_9'                 => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_10'                => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_11'                => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_12'                => new sfWidgetFormChoice(array('choices' => array('' => '', 'Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'datos_alojamiento'                 => new sfWidgetFormFilterInput(),
      'acreditado'                        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'idioma_documentacion'              => new sfWidgetFormChoice(array('choices' => array('' => '', 'Español' => 'Español', 'Inglés' => 'Inglés', 'Francés' => 'Francés', 'Italiano' => 'Italiano', 'Portugués' => 'Portugués', 'Polaco' => 'Polaco'))),
      'tickets_comida'                    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'acreditacion_entregada'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'created_at'                        => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'updated_at'                        => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'turnos_list'                       => new sfWidgetFormDoctrineChoice(array('multiple' => true, 'model' => 'Turno')),
    ));

    $this->setValidators(array(
      'deleted_at'                        => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'nombre'                            => new sfValidatorPass(array('required' => false)),
      'primer_apellido'                   => new sfValidatorPass(array('required' => false)),
      'segundo_apellido'                  => new sfValidatorPass(array('required' => false)),
      'tipo_documento_identificativo'     => new sfValidatorChoice(array('required' => false, 'choices' => array('NIF' => 'NIF', 'Pasaporte' => 'Pasaporte', 'NIE' => 'NIE', 'Otro documento' => 'Otro documento'))),
      'numero_documento_identificativo'   => new sfValidatorPass(array('required' => false)),
      'sexo'                              => new sfValidatorChoice(array('required' => false, 'choices' => array('Masculino' => 'Masculino', 'Femenino' => 'Femenino'))),
      'talla'                             => new sfValidatorChoice(array('required' => false, 'choices' => array('S' => 'S', 'M' => 'M', 'L' => 'L', 'XL' => 'XL', 'XXL' => 'XXL', 'XXXL' => 'XXXL'))),
      'nacionalidad'                      => new sfValidatorPass(array('required' => false)),
      'fecha_nacimiento'                  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'pais'                              => new sfValidatorPass(array('required' => false)),
      'provincia_id'                      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Provincia'), 'column' => 'id')),
      'codigo_postal'                     => new sfValidatorPass(array('required' => false)),
      'ciudad'                            => new sfValidatorPass(array('required' => false)),
      'tipo_via'                          => new sfValidatorPass(array('required' => false)),
      'direccion'                         => new sfValidatorPass(array('required' => false)),
      'numero_via'                        => new sfValidatorPass(array('required' => false)),
      'escalera'                          => new sfValidatorPass(array('required' => false)),
      'piso'                              => new sfValidatorPass(array('required' => false)),
      'puerta'                            => new sfValidatorPass(array('required' => false)),
      'telefono_fijo'                     => new sfValidatorPass(array('required' => false)),
      'telefono_movil'                    => new sfValidatorPass(array('required' => false)),
      'fax'                               => new sfValidatorPass(array('required' => false)),
      'email'                             => new sfValidatorPass(array('required' => false)),
      'nivel_estudios'                    => new sfValidatorChoice(array('required' => false, 'choices' => array('Sin estudios' => 'Sin estudios', 'Estudios básicos' => 'Estudios básicos', 'Bachillerato' => 'Bachillerato', 'Formación profesional' => 'Formación profesional', 'Diplomatura o Ingeniería Técnica' => 'Diplomatura o Ingeniería Técnica', 'Licenciatura o Ingeniería Superior' => 'Licenciatura o Ingeniería Superior'))),
      'especialidad'                      => new sfValidatorPass(array('required' => false)),
      'otros_estudios'                    => new sfValidatorPass(array('required' => false)),
      'nivel_ingles'                      => new sfValidatorChoice(array('required' => false, 'choices' => array('No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'nivel_frances'                     => new sfValidatorChoice(array('required' => false, 'choices' => array('No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'nivel_aleman'                      => new sfValidatorChoice(array('required' => false, 'choices' => array('No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'otro_idioma'                       => new sfValidatorPass(array('required' => false)),
      'nivel_otro_idioma'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('No' => 'No', 'Bajo' => 'Bajo', 'Medio' => 'Medio', 'Alto' => 'Alto'))),
      'experiencia_administracion'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_turismo'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_informatica'           => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_seguridad'             => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_educacion'             => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_sanitario'             => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_traduccion'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_recursos_humanos'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_otro'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_otro_campo'            => new sfValidatorPass(array('required' => false)),
      'experiencia_voluntario'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'experiencia_voluntario_donde'      => new sfValidatorPass(array('required' => false)),
      'experiencia_trato_discapacitados'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'carnet_conducir'                   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'parroquia_id'                      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Parroquia'), 'column' => 'id')),
      'compromiso_religioso'              => new sfValidatorChoice(array('required' => false, 'choices' => array('Básico' => 'Básico', 'Laico comprometido' => 'Laico comprometido', 'Catequista' => 'Catequista', 'Ministro de la comunión' => 'Ministro de la comunión'))),
      'movimiento_id'                     => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Movimiento'), 'column' => 'id')),
      'disponibilidad_dias'               => new sfValidatorChoice(array('required' => false, 'choices' => array('Fines de semana' => 'Fines de semana', 'De lunes a viernes' => 'De lunes a viernes', 'Toda la semana' => 'Toda la semana'))),
      'disponibilidad_horas'              => new sfValidatorChoice(array('required' => false, 'choices' => array('Mañana' => 'Mañana', 'Tarde' => 'Tarde', 'Indiferente' => 'Indiferente'))),
      'colaborar_acogida'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'colaborar_viacrucis'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'colaborar_vigilia'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'colaborar_despedida'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'colaborar_ambientacion'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'colaborar_protocolo'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'colaborar_ministro_comunion'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'autorizacion_boletin'              => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'autorizacion_diocesis'             => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'aceptacion_condiciones'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'alojamiento'                       => new sfValidatorChoice(array('required' => false, 'choices' => array('' => '', 'Domicilio personal' => 'Domicilio personal', 'IFEMA' => 'IFEMA', 'Polideportivo' => 'Polideportivo', 'Albergue' => 'Albergue', 'Otro domicilio' => 'Otro domicilio'))),
      'apto'                              => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'revisado_policia'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'jefe_equipo'                       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'notas'                             => new sfValidatorPass(array('required' => false)),
      'reunion_inicial'                   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'equipo_id'                         => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Equipo'), 'column' => 'id')),
      'foto'                              => new sfValidatorPass(array('required' => false)),
      'pagado'                            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'entrevista_seleccion'              => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'abono_transporte'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('Primera y segunda semana' => 'Primera y segunda semana', 'Sólo segunda semana' => 'Sólo segunda semana'))),
      'numero_acreditacion'               => new sfValidatorPass(array('required' => false)),
      'registrado'                        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'documento_identificacion_personal' => new sfValidatorPass(array('required' => false)),
      'documento_acreditacion'            => new sfValidatorPass(array('required' => false)),
      'documento_compromiso'              => new sfValidatorPass(array('required' => false)),
      'documento_antecedentes_penales'    => new sfValidatorPass(array('required' => false)),
      'documento_autorizacion_paterna'    => new sfValidatorPass(array('required' => false)),
      'medio_transporte'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('Ninguno' => 'Ninguno', 'Avión' => 'Avión', 'Tren' => 'Tren', 'Autobús' => 'Autobús', 'Coche' => 'Coche'))),
      'fecha_llegada'                     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'fecha_salida'                      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'datos_transporte'                  => new sfValidatorPass(array('required' => false)),
      'nivel_seguridad_1'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_2'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_3'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_4'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_5'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_6'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_7'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_8'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_9'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_10'                => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_11'                => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'nivel_seguridad_12'                => new sfValidatorChoice(array('required' => false, 'choices' => array('Nulo' => 'Nulo', 'Gris' => 'Gris', 'Azul' => 'Azul', 'Rojo' => 'Rojo'))),
      'datos_alojamiento'                 => new sfValidatorPass(array('required' => false)),
      'acreditado'                        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'idioma_documentacion'              => new sfValidatorChoice(array('required' => false, 'choices' => array('Español' => 'Español', 'Inglés' => 'Inglés', 'Francés' => 'Francés', 'Italiano' => 'Italiano', 'Portugués' => 'Portugués', 'Polaco' => 'Polaco'))),
      'tickets_comida'                    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'acreditacion_entregada'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'created_at'                        => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'updated_at'                        => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'turnos_list'                       => new sfValidatorDoctrineChoice(array('multiple' => true, 'model' => 'Turno', 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('voluntario_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function addTurnosListColumnQuery(Doctrine_Query $query, $field, $values)
  {
    if (!is_array($values))
    {
      $values = array($values);
    }

    if (!count($values))
    {
      return;
    }

    $query
      ->leftJoin($query->getRootAlias().'.TurnoVoluntario TurnoVoluntario')
      ->andWhereIn('TurnoVoluntario.turno_id', $values)
    ;
  }

  public function getModelName()
  {
    return 'Voluntario';
  }

  public function getFields()
  {
    return array(
      'id'                                => 'Number',
      'deleted_at'                        => 'Date',
      'nombre'                            => 'Text',
      'primer_apellido'                   => 'Text',
      'segundo_apellido'                  => 'Text',
      'tipo_documento_identificativo'     => 'Enum',
      'numero_documento_identificativo'   => 'Text',
      'sexo'                              => 'Enum',
      'talla'                             => 'Enum',
      'nacionalidad'                      => 'Text',
      'fecha_nacimiento'                  => 'Date',
      'pais'                              => 'Text',
      'provincia_id'                      => 'ForeignKey',
      'codigo_postal'                     => 'Text',
      'ciudad'                            => 'Text',
      'tipo_via'                          => 'Text',
      'direccion'                         => 'Text',
      'numero_via'                        => 'Text',
      'escalera'                          => 'Text',
      'piso'                              => 'Text',
      'puerta'                            => 'Text',
      'telefono_fijo'                     => 'Text',
      'telefono_movil'                    => 'Text',
      'fax'                               => 'Text',
      'email'                             => 'Text',
      'nivel_estudios'                    => 'Enum',
      'especialidad'                      => 'Text',
      'otros_estudios'                    => 'Text',
      'nivel_ingles'                      => 'Enum',
      'nivel_frances'                     => 'Enum',
      'nivel_aleman'                      => 'Enum',
      'otro_idioma'                       => 'Text',
      'nivel_otro_idioma'                 => 'Enum',
      'experiencia_administracion'        => 'Boolean',
      'experiencia_turismo'               => 'Boolean',
      'experiencia_informatica'           => 'Boolean',
      'experiencia_seguridad'             => 'Boolean',
      'experiencia_educacion'             => 'Boolean',
      'experiencia_sanitario'             => 'Boolean',
      'experiencia_traduccion'            => 'Boolean',
      'experiencia_recursos_humanos'      => 'Boolean',
      'experiencia_otro'                  => 'Boolean',
      'experiencia_otro_campo'            => 'Text',
      'experiencia_voluntario'            => 'Boolean',
      'experiencia_voluntario_donde'      => 'Text',
      'experiencia_trato_discapacitados'  => 'Boolean',
      'carnet_conducir'                   => 'Boolean',
      'parroquia_id'                      => 'ForeignKey',
      'compromiso_religioso'              => 'Enum',
      'movimiento_id'                     => 'ForeignKey',
      'disponibilidad_dias'               => 'Enum',
      'disponibilidad_horas'              => 'Enum',
      'colaborar_acogida'                 => 'Boolean',
      'colaborar_viacrucis'               => 'Boolean',
      'colaborar_vigilia'                 => 'Boolean',
      'colaborar_despedida'               => 'Boolean',
      'colaborar_ambientacion'            => 'Boolean',
      'colaborar_protocolo'               => 'Boolean',
      'colaborar_ministro_comunion'       => 'Boolean',
      'autorizacion_boletin'              => 'Boolean',
      'autorizacion_diocesis'             => 'Boolean',
      'aceptacion_condiciones'            => 'Boolean',
      'alojamiento'                       => 'Enum',
      'apto'                              => 'Boolean',
      'revisado_policia'                  => 'Boolean',
      'jefe_equipo'                       => 'Boolean',
      'notas'                             => 'Text',
      'reunion_inicial'                   => 'Boolean',
      'equipo_id'                         => 'ForeignKey',
      'foto'                              => 'Text',
      'pagado'                            => 'Boolean',
      'entrevista_seleccion'              => 'Boolean',
      'abono_transporte'                  => 'Enum',
      'numero_acreditacion'               => 'Text',
      'registrado'                        => 'Boolean',
      'documento_identificacion_personal' => 'Text',
      'documento_acreditacion'            => 'Text',
      'documento_compromiso'              => 'Text',
      'documento_antecedentes_penales'    => 'Text',
      'documento_autorizacion_paterna'    => 'Text',
      'medio_transporte'                  => 'Enum',
      'fecha_llegada'                     => 'Date',
      'fecha_salida'                      => 'Date',
      'datos_transporte'                  => 'Text',
      'nivel_seguridad_1'                 => 'Enum',
      'nivel_seguridad_2'                 => 'Enum',
      'nivel_seguridad_3'                 => 'Enum',
      'nivel_seguridad_4'                 => 'Enum',
      'nivel_seguridad_5'                 => 'Enum',
      'nivel_seguridad_6'                 => 'Enum',
      'nivel_seguridad_7'                 => 'Enum',
      'nivel_seguridad_8'                 => 'Enum',
      'nivel_seguridad_9'                 => 'Enum',
      'nivel_seguridad_10'                => 'Enum',
      'nivel_seguridad_11'                => 'Enum',
      'nivel_seguridad_12'                => 'Enum',
      'datos_alojamiento'                 => 'Text',
      'acreditado'                        => 'Boolean',
      'idioma_documentacion'              => 'Enum',
      'tickets_comida'                    => 'Boolean',
      'acreditacion_entregada'            => 'Boolean',
      'created_at'                        => 'Date',
      'updated_at'                        => 'Date',
      'turnos_list'                       => 'ManyKey',
    );
  }
}
