<?php

/**
 * BaseVoluntario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $deleted_at
 * @property string $nombre
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property enum $tipo_documento_identificativo
 * @property string $numero_documento_identificativo
 * @property enum $sexo
 * @property enum $talla
 * @property string $nacionalidad
 * @property date $fecha_nacimiento
 * @property string $pais
 * @property  $provincia_id
 * @property string $codigo_postal
 * @property string $ciudad
 * @property string $tipo_via
 * @property string $direccion
 * @property string $numero_via
 * @property string $escalera
 * @property string $piso
 * @property string $puerta
 * @property string $telefono_fijo
 * @property string $telefono_movil
 * @property string $fax
 * @property string $email
 * @property enum $nivel_estudios
 * @property string $especialidad
 * @property string $otros_estudios
 * @property enum $nivel_ingles
 * @property enum $nivel_frances
 * @property enum $nivel_aleman
 * @property string $otro_idioma
 * @property enum $nivel_otro_idioma
 * @property boolean $experiencia_administracion
 * @property boolean $experiencia_turismo
 * @property boolean $experiencia_informatica
 * @property boolean $experiencia_seguridad
 * @property boolean $experiencia_educacion
 * @property boolean $experiencia_sanitario
 * @property boolean $experiencia_traduccion
 * @property boolean $experiencia_recursos_humanos
 * @property boolean $experiencia_otro
 * @property string $experiencia_otro_campo
 * @property boolean $experiencia_voluntario
 * @property string $experiencia_voluntario_donde
 * @property boolean $experiencia_trato_discapacitados
 * @property boolean $carnet_conducir
 * @property integer $parroquia_id
 * @property enum $compromiso_religioso
 * @property integer $movimiento_id
 * @property enum $disponibilidad_dias
 * @property enum $disponibilidad_horas
 * @property boolean $colaborar_acogida
 * @property boolean $colaborar_viacrucis
 * @property boolean $colaborar_vigilia
 * @property boolean $colaborar_despedida
 * @property boolean $colaborar_ambientacion
 * @property boolean $colaborar_protocolo
 * @property boolean $colaborar_ministro_comunion
 * @property boolean $autorizacion_boletin
 * @property boolean $autorizacion_diocesis
 * @property boolean $aceptacion_condiciones
 * @property enum $alojamiento
 * @property boolean $apto
 * @property boolean $revisado_policia
 * @property boolean $jefe_equipo
 * @property string $notas
 * @property boolean $reunion_inicial
 * @property  $equipo_id
 * @property string $foto
 * @property boolean $pagado
 * @property boolean $entrevista_seleccion
 * @property enum $abono_transporte
 * @property string $numero_acreditacion
 * @property boolean $registrado
 * @property string $documento_identificacion_personal
 * @property string $documento_acreditacion
 * @property string $documento_compromiso
 * @property string $documento_antecedentes_penales
 * @property string $documento_autorizacion_paterna
 * @property enum $medio_transporte
 * @property timestamp $fecha_llegada
 * @property timestamp $fecha_salida
 * @property string $datos_transporte
 * @property enum $nivel_seguridad_1
 * @property enum $nivel_seguridad_2
 * @property enum $nivel_seguridad_3
 * @property enum $nivel_seguridad_4
 * @property enum $nivel_seguridad_5
 * @property enum $nivel_seguridad_6
 * @property enum $nivel_seguridad_7
 * @property enum $nivel_seguridad_8
 * @property enum $nivel_seguridad_9
 * @property enum $nivel_seguridad_10
 * @property enum $nivel_seguridad_11
 * @property enum $nivel_seguridad_12
 * @property string $datos_alojamiento
 * @property boolean $acreditado
 * @property enum $idioma_documentacion
 * @property boolean $tickets_comida
 * @property boolean $acreditacion_entregada
 * @property Equipo $Equipo
 * @property Provincia $Provincia
 * @property Parroquia $Parroquia
 * @property Movimiento $Movimiento
 * @property Doctrine_Collection $Tareas
 * @property Doctrine_Collection $TareaRadioportatil
 * @property Doctrine_Collection $Turnos
 * @property Doctrine_Collection $TurnosVoluntario
 * 
 * @method date                getDeletedAt()                         Returns the current record's "deleted_at" value
 * @method string              getNombre()                            Returns the current record's "nombre" value
 * @method string              getPrimerApellido()                    Returns the current record's "primer_apellido" value
 * @method string              getSegundoApellido()                   Returns the current record's "segundo_apellido" value
 * @method enum                getTipoDocumentoIdentificativo()       Returns the current record's "tipo_documento_identificativo" value
 * @method string              getNumeroDocumentoIdentificativo()     Returns the current record's "numero_documento_identificativo" value
 * @method enum                getSexo()                              Returns the current record's "sexo" value
 * @method enum                getTalla()                             Returns the current record's "talla" value
 * @method string              getNacionalidad()                      Returns the current record's "nacionalidad" value
 * @method date                getFechaNacimiento()                   Returns the current record's "fecha_nacimiento" value
 * @method string              getPais()                              Returns the current record's "pais" value
 * @method string              getCodigoPostal()                      Returns the current record's "codigo_postal" value
 * @method string              getCiudad()                            Returns the current record's "ciudad" value
 * @method string              getTipoVia()                           Returns the current record's "tipo_via" value
 * @method string              getDireccion()                         Returns the current record's "direccion" value
 * @method string              getNumeroVia()                         Returns the current record's "numero_via" value
 * @method string              getEscalera()                          Returns the current record's "escalera" value
 * @method string              getPiso()                              Returns the current record's "piso" value
 * @method string              getPuerta()                            Returns the current record's "puerta" value
 * @method string              getTelefonoFijo()                      Returns the current record's "telefono_fijo" value
 * @method string              getTelefonoMovil()                     Returns the current record's "telefono_movil" value
 * @method string              getFax()                               Returns the current record's "fax" value
 * @method string              getEmail()                             Returns the current record's "email" value
 * @method enum                getNivelEstudios()                     Returns the current record's "nivel_estudios" value
 * @method string              getEspecialidad()                      Returns the current record's "especialidad" value
 * @method string              getOtrosEstudios()                     Returns the current record's "otros_estudios" value
 * @method enum                getNivelIngles()                       Returns the current record's "nivel_ingles" value
 * @method enum                getNivelFrances()                      Returns the current record's "nivel_frances" value
 * @method enum                getNivelAleman()                       Returns the current record's "nivel_aleman" value
 * @method string              getOtroIdioma()                        Returns the current record's "otro_idioma" value
 * @method enum                getNivelOtroIdioma()                   Returns the current record's "nivel_otro_idioma" value
 * @method boolean             getExperienciaAdministracion()         Returns the current record's "experiencia_administracion" value
 * @method boolean             getExperienciaTurismo()                Returns the current record's "experiencia_turismo" value
 * @method boolean             getExperienciaInformatica()            Returns the current record's "experiencia_informatica" value
 * @method boolean             getExperienciaSeguridad()              Returns the current record's "experiencia_seguridad" value
 * @method boolean             getExperienciaEducacion()              Returns the current record's "experiencia_educacion" value
 * @method boolean             getExperienciaSanitario()              Returns the current record's "experiencia_sanitario" value
 * @method boolean             getExperienciaTraduccion()             Returns the current record's "experiencia_traduccion" value
 * @method boolean             getExperienciaRecursosHumanos()        Returns the current record's "experiencia_recursos_humanos" value
 * @method boolean             getExperienciaOtro()                   Returns the current record's "experiencia_otro" value
 * @method string              getExperienciaOtroCampo()              Returns the current record's "experiencia_otro_campo" value
 * @method boolean             getExperienciaVoluntario()             Returns the current record's "experiencia_voluntario" value
 * @method string              getExperienciaVoluntarioDonde()        Returns the current record's "experiencia_voluntario_donde" value
 * @method boolean             getExperienciaTratoDiscapacitados()    Returns the current record's "experiencia_trato_discapacitados" value
 * @method boolean             getCarnetConducir()                    Returns the current record's "carnet_conducir" value
 * @method integer             getParroquiaId()                       Returns the current record's "parroquia_id" value
 * @method enum                getCompromisoReligioso()               Returns the current record's "compromiso_religioso" value
 * @method integer             getMovimientoId()                      Returns the current record's "movimiento_id" value
 * @method enum                getDisponibilidadDias()                Returns the current record's "disponibilidad_dias" value
 * @method enum                getDisponibilidadHoras()               Returns the current record's "disponibilidad_horas" value
 * @method boolean             getColaborarAcogida()                  Returns the current record's "colaborar_acogida" value
 * @method boolean             getColaborarViacrucis()                Returns the current record's "colaborar_viacrucis" value
 * @method boolean             getColaborarVigilia()                  Returns the current record's "colaborar_vigilia" value
 * @method boolean             getColaborarDespedida()                Returns the current record's "colaborar_despedida" value
 * @method boolean             getColaborarAmbientacion()             Returns the current record's "colaborar_ambientacion" value
 * @method boolean             getColaborarProtocolo()                Returns the current record's "colaborar_protocolo" value
 * @method boolean             getColaborarMinistroComunion()         Returns the current record's "colaborar_ministro_comunion" value
 * @method boolean             getAutorizacionBoletin()               Returns the current record's "autorizacion_boletin" value
 * @method boolean             getAutorizacionDiocesis()              Returns the current record's "autorizacion_diocesis" value
 * @method boolean             getAceptacionCondiciones()             Returns the current record's "aceptacion_condiciones" value
 * @method enum                getAlojamiento()                       Returns the current record's "alojamiento" value
 * @method boolean             getApto()                              Returns the current record's "apto" value
 * @method boolean             getRevisadoPolicia()                   Returns the current record's "revisado_policia" value
 * @method boolean             getJefeEquipo()                        Returns the current record's "jefe_equipo" value
 * @method string              getNotas()                             Returns the current record's "notas" value
 * @method boolean             getReunionInicial()                    Returns the current record's "reunion_inicial" value
 * @method string              getFoto()                              Returns the current record's "foto" value
 * @method boolean             getPagado()                            Returns the current record's "pagado" value
 * @method boolean             getEntrevistaSeleccion()               Returns the current record's "entrevista_seleccion" value
 * @method enum                getAbonoTransporte()                   Returns the current record's "abono_transporte" value
 * @method string              getNumeroAcreditacion()                Returns the current record's "numero_acreditacion" value
 * @method boolean             getRegistrado()                        Returns the current record's "registrado" value
 * @method string              getDocumentoIdentificacionPersonal()   Returns the current record's "documento_identificacion_personal" value
 * @method string              getDocumentoAcreditacion()             Returns the current record's "documento_acreditacion" value
 * @method string              getDocumentoCompromiso()               Returns the current record's "documento_compromiso" value
 * @method string              getDocumentoAntecedentesPenales()      Returns the current record's "documento_antecedentes_penales" value
 * @method string              getDocumentoAutorizacionPaterna()      Returns the current record's "documento_autorizacion_paterna" value
 * @method enum                getMedioTransporte()                   Returns the current record's "medio_transporte" value
 * @method timestamp           getFechaLlegada()                      Returns the current record's "fecha_llegada" value
 * @method timestamp           getFechaSalida()                       Returns the current record's "fecha_salida" value
 * @method string              getDatosTransporte()                   Returns the current record's "datos_transporte" value
 * @method enum                getNivelSeguridad1()                   Returns the current record's "nivel_seguridad_1" value
 * @method enum                getNivelSeguridad2()                   Returns the current record's "nivel_seguridad_2" value
 * @method enum                getNivelSeguridad3()                   Returns the current record's "nivel_seguridad_3" value
 * @method enum                getNivelSeguridad4()                   Returns the current record's "nivel_seguridad_4" value
 * @method enum                getNivelSeguridad5()                   Returns the current record's "nivel_seguridad_5" value
 * @method enum                getNivelSeguridad6()                   Returns the current record's "nivel_seguridad_6" value
 * @method enum                getNivelSeguridad7()                   Returns the current record's "nivel_seguridad_7" value
 * @method enum                getNivelSeguridad8()                   Returns the current record's "nivel_seguridad_8" value
 * @method enum                getNivelSeguridad9()                   Returns the current record's "nivel_seguridad_9" value
 * @method enum                getNivelSeguridad10()                  Returns the current record's "nivel_seguridad_10" value
 * @method enum                getNivelSeguridad11()                  Returns the current record's "nivel_seguridad_11" value
 * @method enum                getNivelSeguridad12()                  Returns the current record's "nivel_seguridad_12" value
 * @method string              getDatosAlojamiento()                  Returns the current record's "datos_alojamiento" value
 * @method boolean             getAcreditado()                        Returns the current record's "acreditado" value
 * @method enum                getIdiomaDocumentacion()               Returns the current record's "idioma_documentacion" value
 * @method boolean             getTicketsComida()                     Returns the current record's "tickets_comida" value
 * @method boolean             getAcreditacionEntregada()             Returns the current record's "acreditacion_entregada" value
 * @method Equipo              getEquipo()                            Returns the current record's "Equipo" value
 * @method Provincia           getProvincia()                         Returns the current record's "Provincia" value
 * @method Parroquia           getParroquia()                         Returns the current record's "Parroquia" value
 * @method Movimiento          getMovimiento()                        Returns the current record's "Movimiento" value
 * @method Doctrine_Collection getTareas()                            Returns the current record's "Tareas" collection
 * @method Doctrine_Collection getTareaRadioportatil()                Returns the current record's "TareaRadioportatil" collection
 * @method Doctrine_Collection getTurnos()                            Returns the current record's "Turnos" collection
 * @method Doctrine_Collection getTurnosVoluntario()                  Returns the current record's "TurnosVoluntario" collection
 * @method Voluntario          setDeletedAt()                         Sets the current record's "deleted_at" value
 * @method Voluntario          setNombre()                            Sets the current record's "nombre" value
 * @method Voluntario          setPrimerApellido()                    Sets the current record's "primer_apellido" value
 * @method Voluntario          setSegundoApellido()                   Sets the current record's "segundo_apellido" value
 * @method Voluntario          setTipoDocumentoIdentificativo()       Sets the current record's "tipo_documento_identificativo" value
 * @method Voluntario          setNumeroDocumentoIdentificativo()     Sets the current record's "numero_documento_identificativo" value
 * @method Voluntario          setSexo()                              Sets the current record's "sexo" value
 * @method Voluntario          setTalla()                             Sets the current record's "talla" value
 * @method Voluntario          setNacionalidad()                      Sets the current record's "nacionalidad" value
 * @method Voluntario          setFechaNacimiento()                   Sets the current record's "fecha_nacimiento" value
 * @method Voluntario          setPais()                              Sets the current record's "pais" value
 * @method Voluntario          setCodigoPostal()                      Sets the current record's "codigo_postal" value
 * @method Voluntario          setCiudad()                            Sets the current record's "ciudad" value
 * @method Voluntario          setTipoVia()                           Sets the current record's "tipo_via" value
 * @method Voluntario          setDireccion()                         Sets the current record's "direccion" value
 * @method Voluntario          setNumeroVia()                         Sets the current record's "numero_via" value
 * @method Voluntario          setEscalera()                          Sets the current record's "escalera" value
 * @method Voluntario          setPiso()                              Sets the current record's "piso" value
 * @method Voluntario          setPuerta()                            Sets the current record's "puerta" value
 * @method Voluntario          setTelefonoFijo()                      Sets the current record's "telefono_fijo" value
 * @method Voluntario          setTelefonoMovil()                     Sets the current record's "telefono_movil" value
 * @method Voluntario          setFax()                               Sets the current record's "fax" value
 * @method Voluntario          setEmail()                             Sets the current record's "email" value
 * @method Voluntario          setNivelEstudios()                     Sets the current record's "nivel_estudios" value
 * @method Voluntario          setEspecialidad()                      Sets the current record's "especialidad" value
 * @method Voluntario          setOtrosEstudios()                     Sets the current record's "otros_estudios" value
 * @method Voluntario          setNivelIngles()                       Sets the current record's "nivel_ingles" value
 * @method Voluntario          setNivelFrances()                      Sets the current record's "nivel_frances" value
 * @method Voluntario          setNivelAleman()                       Sets the current record's "nivel_aleman" value
 * @method Voluntario          setOtroIdioma()                        Sets the current record's "otro_idioma" value
 * @method Voluntario          setNivelOtroIdioma()                   Sets the current record's "nivel_otro_idioma" value
 * @method Voluntario          setExperienciaAdministracion()         Sets the current record's "experiencia_administracion" value
 * @method Voluntario          setExperienciaTurismo()                Sets the current record's "experiencia_turismo" value
 * @method Voluntario          setExperienciaInformatica()            Sets the current record's "experiencia_informatica" value
 * @method Voluntario          setExperienciaSeguridad()              Sets the current record's "experiencia_seguridad" value
 * @method Voluntario          setExperienciaEducacion()              Sets the current record's "experiencia_educacion" value
 * @method Voluntario          setExperienciaSanitario()              Sets the current record's "experiencia_sanitario" value
 * @method Voluntario          setExperienciaTraduccion()             Sets the current record's "experiencia_traduccion" value
 * @method Voluntario          setExperienciaRecursosHumanos()        Sets the current record's "experiencia_recursos_humanos" value
 * @method Voluntario          setExperienciaOtro()                   Sets the current record's "experiencia_otro" value
 * @method Voluntario          setExperienciaOtroCampo()              Sets the current record's "experiencia_otro_campo" value
 * @method Voluntario          setExperienciaVoluntario()             Sets the current record's "experiencia_voluntario" value
 * @method Voluntario          setExperienciaVoluntarioDonde()        Sets the current record's "experiencia_voluntario_donde" value
 * @method Voluntario          setExperienciaTratoDiscapacitados()    Sets the current record's "experiencia_trato_discapacitados" value
 * @method Voluntario          setCarnetConducir()                    Sets the current record's "carnet_conducir" value
 * @method Voluntario          setParroquiaId()                       Sets the current record's "parroquia_id" value
 * @method Voluntario          setCompromisoReligioso()               Sets the current record's "compromiso_religioso" value
 * @method Voluntario          setMovimientoId()                      Sets the current record's "movimiento_id" value
 * @method Voluntario          setDisponibilidadDias()                Sets the current record's "disponibilidad_dias" value
 * @method Voluntario          setDisponibilidadHoras()               Sets the current record's "disponibilidad_horas" value
 * @method Voluntario          setColaborarAcogida()                  Sets the current record's "colaborar_acogida" value
 * @method Voluntario          setColaborarViacrucis()                Sets the current record's "colaborar_viacrucis" value
 * @method Voluntario          setColaborarVigilia()                  Sets the current record's "colaborar_vigilia" value
 * @method Voluntario          setColaborarDespedida()                Sets the current record's "colaborar_despedida" value
 * @method Voluntario          setColaborarAmbientacion()             Sets the current record's "colaborar_ambientacion" value
 * @method Voluntario          setColaborarProtocolo()                Sets the current record's "colaborar_protocolo" value
 * @method Voluntario          setColaborarMinistroComunion()         Sets the current record's "colaborar_ministro_comunion" value
 * @method Voluntario          setAutorizacionBoletin()               Sets the current record's "autorizacion_boletin" value
 * @method Voluntario          setAutorizacionDiocesis()              Sets the current record's "autorizacion_diocesis" value
 * @method Voluntario          setAceptacionCondiciones()             Sets the current record's "aceptacion_condiciones" value
 * @method Voluntario          setAlojamiento()                       Sets the current record's "alojamiento" value
 * @method Voluntario          setApto()                              Sets the current record's "apto" value
 * @method Voluntario          setRevisadoPolicia()                   Sets the current record's "revisado_policia" value
 * @method Voluntario          setJefeEquipo()                        Sets the current record's "jefe_equipo" value
 * @method Voluntario          setNotas()                             Sets the current record's "notas" value
 * @method Voluntario          setReunionInicial()                    Sets the current record's "reunion_inicial" value
 * @method Voluntario          setFoto()                              Sets the current record's "foto" value
 * @method Voluntario          setPagado()                            Sets the current record's "pagado" value
 * @method Voluntario          setEntrevistaSeleccion()               Sets the current record's "entrevista_seleccion" value
 * @method Voluntario          setAbonoTransporte()                   Sets the current record's "abono_transporte" value
 * @method Voluntario          setNumeroAcreditacion()                Sets the current record's "numero_acreditacion" value
 * @method Voluntario          setRegistrado()                        Sets the current record's "registrado" value
 * @method Voluntario          setDocumentoIdentificacionPersonal()   Sets the current record's "documento_identificacion_personal" value
 * @method Voluntario          setDocumentoAcreditacion()             Sets the current record's "documento_acreditacion" value
 * @method Voluntario          setDocumentoCompromiso()               Sets the current record's "documento_compromiso" value
 * @method Voluntario          setDocumentoAntecedentesPenales()      Sets the current record's "documento_antecedentes_penales" value
 * @method Voluntario          setDocumentoAutorizacionPaterna()      Sets the current record's "documento_autorizacion_paterna" value
 * @method Voluntario          setMedioTransporte()                   Sets the current record's "medio_transporte" value
 * @method Voluntario          setFechaLlegada()                      Sets the current record's "fecha_llegada" value
 * @method Voluntario          setFechaSalida()                       Sets the current record's "fecha_salida" value
 * @method Voluntario          setDatosTransporte()                   Sets the current record's "datos_transporte" value
 * @method Voluntario          setNivelSeguridad1()                   Sets the current record's "nivel_seguridad_1" value
 * @method Voluntario          setNivelSeguridad2()                   Sets the current record's "nivel_seguridad_2" value
 * @method Voluntario          setNivelSeguridad3()                   Sets the current record's "nivel_seguridad_3" value
 * @method Voluntario          setNivelSeguridad4()                   Sets the current record's "nivel_seguridad_4" value
 * @method Voluntario          setNivelSeguridad5()                   Sets the current record's "nivel_seguridad_5" value
 * @method Voluntario          setNivelSeguridad6()                   Sets the current record's "nivel_seguridad_6" value
 * @method Voluntario          setNivelSeguridad7()                   Sets the current record's "nivel_seguridad_7" value
 * @method Voluntario          setNivelSeguridad8()                   Sets the current record's "nivel_seguridad_8" value
 * @method Voluntario          setNivelSeguridad9()                   Sets the current record's "nivel_seguridad_9" value
 * @method Voluntario          setNivelSeguridad10()                  Sets the current record's "nivel_seguridad_10" value
 * @method Voluntario          setNivelSeguridad11()                  Sets the current record's "nivel_seguridad_11" value
 * @method Voluntario          setNivelSeguridad12()                  Sets the current record's "nivel_seguridad_12" value
 * @method Voluntario          setDatosAlojamiento()                  Sets the current record's "datos_alojamiento" value
 * @method Voluntario          setAcreditado()                        Sets the current record's "acreditado" value
 * @method Voluntario          setIdiomaDocumentacion()               Sets the current record's "idioma_documentacion" value
 * @method Voluntario          setTicketsComida()                     Sets the current record's "tickets_comida" value
 * @method Voluntario          setAcreditacionEntregada()             Sets the current record's "acreditacion_entregada" value
 * @method Voluntario          setEquipo()                            Sets the current record's "Equipo" value
 * @method Voluntario          setProvincia()                         Sets the current record's "Provincia" value
 * @method Voluntario          setParroquia()                         Sets the current record's "Parroquia" value
 * @method Voluntario          setMovimiento()                        Sets the current record's "Movimiento" value
 * @method Voluntario          setTareas()                            Sets the current record's "Tareas" collection
 * @method Voluntario          setTareaRadioportatil()                Sets the current record's "TareaRadioportatil" collection
 * @method Voluntario          setTurnos()                            Sets the current record's "Turnos" collection
 * @method Voluntario          setTurnosVoluntario()                  Sets the current record's "TurnosVoluntario" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVoluntario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('voluntario');
        $this->hasColumn('deleted_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('primer_apellido', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('segundo_apellido', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tipo_documento_identificativo', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'NIF',
              1 => 'Pasaporte',
              2 => 'NIE',
              3 => 'Otro documento',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('numero_documento_identificativo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sexo', 'enum', 9, array(
             'type' => 'enum',
             'length' => 9,
             'values' => 
             array(
              0 => 'Masculino',
              1 => 'Femenino',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('talla', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'S',
              1 => 'M',
              2 => 'L',
              3 => 'XL',
              4 => 'XXL',
              5 => 'XXXL',
             ),
             ));
        $this->hasColumn('nacionalidad', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('pais', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('provincia_id', '', null);
        $this->hasColumn('codigo_postal', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ciudad', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo_via', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('numero_via', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('escalera', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('piso', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('puerta', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('telefono_fijo', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('telefono_movil', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('fax', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nivel_estudios', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Sin estudios',
              1 => 'Estudios básicos',
              2 => 'Bachillerato',
              3 => 'Formación profesional',
              4 => 'Diplomatura o Ingeniería Técnica',
              5 => 'Licenciatura o Ingeniería Superior',
             ),
             ));
        $this->hasColumn('especialidad', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('otros_estudios', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nivel_ingles', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'No',
              1 => 'Bajo',
              2 => 'Medio',
              3 => 'Alto',
             ),
             ));
        $this->hasColumn('nivel_frances', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'No',
              1 => 'Bajo',
              2 => 'Medio',
              3 => 'Alto',
             ),
             ));
        $this->hasColumn('nivel_aleman', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'No',
              1 => 'Bajo',
              2 => 'Medio',
              3 => 'Alto',
             ),
             ));
        $this->hasColumn('otro_idioma', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nivel_otro_idioma', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'No',
              1 => 'Bajo',
              2 => 'Medio',
              3 => 'Alto',
             ),
             ));
        $this->hasColumn('experiencia_administracion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_turismo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_informatica', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_seguridad', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_educacion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_sanitario', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_traduccion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_recursos_humanos', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_otro', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_otro_campo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('experiencia_voluntario', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('experiencia_voluntario_donde', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('experiencia_trato_discapacitados', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('carnet_conducir', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('parroquia_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('compromiso_religioso', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Básico',
              1 => 'Laico comprometido',
              2 => 'Catequista',
              3 => 'Ministro de la comunión',
             ),
             ));
        $this->hasColumn('movimiento_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('disponibilidad_dias', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Fines de semana',
              1 => 'De lunes a viernes',
              2 => 'Toda la semana',
             ),
             ));
        $this->hasColumn('disponibilidad_horas', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Mañana',
              1 => 'Tarde',
              2 => 'Indiferente',
             ),
             ));
        $this->hasColumn('colaborar_acogida', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('colaborar_viacrucis', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('colaborar_vigilia', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('colaborar_despedida', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('colaborar_ambientacion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('colaborar_protocolo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('colaborar_ministro_comunion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('autorizacion_boletin', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('autorizacion_diocesis', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('aceptacion_condiciones', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('alojamiento', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '',
              1 => 'Domicilio personal',
              2 => 'IFEMA',
              3 => 'Polideportivo',
              4 => 'Albergue',
              5 => 'Otro domicilio',
             ),
             ));
        $this->hasColumn('apto', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('revisado_policia', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('jefe_equipo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('notas', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('reunion_inicial', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('equipo_id', '', null);
        $this->hasColumn('foto', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pagado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('entrevista_seleccion', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('abono_transporte', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Primera y segunda semana',
              1 => 'Sólo segunda semana',
             ),
             ));
        $this->hasColumn('numero_acreditacion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('registrado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('documento_identificacion_personal', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('documento_acreditacion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('documento_compromiso', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('documento_antecedentes_penales', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('documento_autorizacion_paterna', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('medio_transporte', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Ninguno',
              1 => 'Avión',
              2 => 'Tren',
              3 => 'Autobús',
              4 => 'Coche',
             ),
             ));
        $this->hasColumn('fecha_llegada', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fecha_salida', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('datos_transporte', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('nivel_seguridad_1', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_2', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_3', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_4', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_5', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_6', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_7', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_8', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_9', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_10', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_11', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('nivel_seguridad_12', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Nulo',
              1 => 'Gris',
              2 => 'Azul',
              3 => 'Rojo',
             ),
             'notnull' => true,
             'default' => 'Nulo',
             ));
        $this->hasColumn('datos_alojamiento', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('acreditado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('idioma_documentacion', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Español',
              1 => 'Inglés',
              2 => 'Francés',
              3 => 'Italiano',
              4 => 'Portugués',
              5 => 'Polaco',
             ),
             ));
        $this->hasColumn('tickets_comida', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('acreditacion_entregada', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Equipo', array(
             'local' => 'equipo_id',
             'foreign' => 'id'));

        $this->hasOne('Provincia', array(
             'local' => 'provincia_id',
             'foreign' => 'id'));

        $this->hasOne('Parroquia', array(
             'local' => 'parroquia_id',
             'foreign' => 'id'));

        $this->hasOne('Movimiento', array(
             'local' => 'movimiento_id',
             'foreign' => 'id'));

        $this->hasMany('Tarea as Tareas', array(
             'local' => 'id',
             'foreign' => 'voluntario_id'));

        $this->hasMany('TareaRadioportatil', array(
             'local' => 'id',
             'foreign' => 'voluntario_id'));

        $this->hasMany('Turno as Turnos', array(
             'refClass' => 'TurnoVoluntario',
             'local' => 'voluntario_id',
             'foreign' => 'turno_id'));

        $this->hasMany('TurnoVoluntario as TurnosVoluntario', array(
             'local' => 'id',
             'foreign' => 'voluntario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($softdelete0);
    }
}