<?php

/**
 * BaseParroquia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $municipio
 * @property integer $arciprestazgo_id
 * @property Arciprestazgo $Arciprestazgo
 * @property Doctrine_Collection $Voluntario
 * 
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getMunicipio()        Returns the current record's "municipio" value
 * @method integer             getArciprestazgoId()  Returns the current record's "arciprestazgo_id" value
 * @method Arciprestazgo       getArciprestazgo()    Returns the current record's "Arciprestazgo" value
 * @method Doctrine_Collection getVoluntario()       Returns the current record's "Voluntario" collection
 * @method Parroquia           setNombre()           Sets the current record's "nombre" value
 * @method Parroquia           setMunicipio()        Sets the current record's "municipio" value
 * @method Parroquia           setArciprestazgoId()  Sets the current record's "arciprestazgo_id" value
 * @method Parroquia           setArciprestazgo()    Sets the current record's "Arciprestazgo" value
 * @method Parroquia           setVoluntario()       Sets the current record's "Voluntario" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParroquia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parroquia');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('municipio', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('arciprestazgo_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Arciprestazgo', array(
             'local' => 'arciprestazgo_id',
             'foreign' => 'id'));

        $this->hasMany('Voluntario', array(
             'local' => 'id',
             'foreign' => 'parroquia_id'));
    }
}