<?php

/**
 * BasePais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $codigo
 * @property Doctrine_Collection $IdiomaPais
 * 
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method string              getCodigo()     Returns the current record's "codigo" value
 * @method Doctrine_Collection getIdiomaPais() Returns the current record's "IdiomaPais" collection
 * @method Pais                setNombre()     Sets the current record's "nombre" value
 * @method Pais                setCodigo()     Sets the current record's "codigo" value
 * @method Pais                setIdiomaPais() Sets the current record's "IdiomaPais" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('codigo', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('IdiomaPais', array(
             'local' => 'id',
             'foreign' => 'pais_id'));
    }
}