<?php

/**
 * BaseTareaRadioportatil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property  $tarea_id
 * @property  $radioportatil_id
 * @property integer $voluntario_id
 * @property Tarea $Tarea
 * @property Radioportatil $Radioportatil
 * @property Voluntario $Voluntario
 * 
 * @method integer            getVoluntarioId()  Returns the current record's "voluntario_id" value
 * @method Tarea              getTarea()         Returns the current record's "Tarea" value
 * @method Radioportatil      getRadioportatil() Returns the current record's "Radioportatil" value
 * @method Voluntario         getVoluntario()    Returns the current record's "Voluntario" value
 * @method TareaRadioportatil setVoluntarioId()  Sets the current record's "voluntario_id" value
 * @method TareaRadioportatil setTarea()         Sets the current record's "Tarea" value
 * @method TareaRadioportatil setRadioportatil() Sets the current record's "Radioportatil" value
 * @method TareaRadioportatil setVoluntario()    Sets the current record's "Voluntario" value
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTareaRadioportatil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarea_radioportatil');
        $this->hasColumn('tarea_id', '', null);
        $this->hasColumn('radioportatil_id', '', null);
        $this->hasColumn('voluntario_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tarea', array(
             'local' => 'tarea_id',
             'foreign' => 'id'));

        $this->hasOne('Radioportatil', array(
             'local' => 'radioportatil_id',
             'foreign' => 'id'));

        $this->hasOne('Voluntario', array(
             'local' => 'voluntario_id',
             'foreign' => 'id'));
    }
}