<?php

/**
 * BaseDiocesis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $Vicaria
 * @property Doctrine_Collection $Arciprestazgo
 * 
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method Doctrine_Collection getVicaria()       Returns the current record's "Vicaria" collection
 * @method Doctrine_Collection getArciprestazgo() Returns the current record's "Arciprestazgo" collection
 * @method Diocesis            setNombre()        Sets the current record's "nombre" value
 * @method Diocesis            setVicaria()       Sets the current record's "Vicaria" collection
 * @method Diocesis            setArciprestazgo() Sets the current record's "Arciprestazgo" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiocesis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('diocesis');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Vicaria', array(
             'local' => 'id',
             'foreign' => 'diocesis_id'));

        $this->hasMany('Arciprestazgo', array(
             'local' => 'id',
             'foreign' => 'diocesis_id'));
    }
}