<?php

/**
 * BaseTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property date $fecha
 * @property enum $franja_horaria
 * @property integer $lugar_id
 * @property string $descripcion
 * @property  $evento_id
 * @property  $voluntario_id
 * @property integer $perfil_id
 * @property integer $voluntarios_necesarios
 * @property enum $estado
 * @property integer $departamento_id
 * @property time $hora_comienzo
 * @property time $hora_fin
 * @property Voluntario $Voluntario
 * @property Evento $Evento
 * @property Lugar $Lugar
 * @property Perfil $Perfil
 * @property Departamento $Departamento
 * @property Doctrine_Collection $Equipos
 * @property Doctrine_Collection $TareaEquipo
 * @property Doctrine_Collection $Radioportatiles
 * @property Doctrine_Collection $TareaRadioportatiles
 * 
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method date                getFecha()                  Returns the current record's "fecha" value
 * @method enum                getFranjaHoraria()          Returns the current record's "franja_horaria" value
 * @method integer             getLugarId()                Returns the current record's "lugar_id" value
 * @method string              getDescripcion()            Returns the current record's "descripcion" value
 * @method integer             getPerfilId()               Returns the current record's "perfil_id" value
 * @method integer             getVoluntariosNecesarios()  Returns the current record's "voluntarios_necesarios" value
 * @method enum                getEstado()                 Returns the current record's "estado" value
 * @method integer             getDepartamentoId()         Returns the current record's "departamento_id" value
 * @method time                getHoraComienzo()           Returns the current record's "hora_comienzo" value
 * @method time                getHoraFin()                Returns the current record's "hora_fin" value
 * @method Voluntario          getVoluntario()             Returns the current record's "Voluntario" value
 * @method Evento              getEvento()                 Returns the current record's "Evento" value
 * @method Lugar               getLugar()                  Returns the current record's "Lugar" value
 * @method Perfil              getPerfil()                 Returns the current record's "Perfil" value
 * @method Departamento        getDepartamento()           Returns the current record's "Departamento" value
 * @method Doctrine_Collection getEquipos()                Returns the current record's "Equipos" collection
 * @method Doctrine_Collection getTareaEquipo()            Returns the current record's "TareaEquipo" collection
 * @method Doctrine_Collection getRadioportatiles()        Returns the current record's "Radioportatiles" collection
 * @method Doctrine_Collection getTareaRadioportatiles()   Returns the current record's "TareaRadioportatiles" collection
 * @method Tarea               setNombre()                 Sets the current record's "nombre" value
 * @method Tarea               setFecha()                  Sets the current record's "fecha" value
 * @method Tarea               setFranjaHoraria()          Sets the current record's "franja_horaria" value
 * @method Tarea               setLugarId()                Sets the current record's "lugar_id" value
 * @method Tarea               setDescripcion()            Sets the current record's "descripcion" value
 * @method Tarea               setPerfilId()               Sets the current record's "perfil_id" value
 * @method Tarea               setVoluntariosNecesarios()  Sets the current record's "voluntarios_necesarios" value
 * @method Tarea               setEstado()                 Sets the current record's "estado" value
 * @method Tarea               setDepartamentoId()         Sets the current record's "departamento_id" value
 * @method Tarea               setHoraComienzo()           Sets the current record's "hora_comienzo" value
 * @method Tarea               setHoraFin()                Sets the current record's "hora_fin" value
 * @method Tarea               setVoluntario()             Sets the current record's "Voluntario" value
 * @method Tarea               setEvento()                 Sets the current record's "Evento" value
 * @method Tarea               setLugar()                  Sets the current record's "Lugar" value
 * @method Tarea               setPerfil()                 Sets the current record's "Perfil" value
 * @method Tarea               setDepartamento()           Sets the current record's "Departamento" value
 * @method Tarea               setEquipos()                Sets the current record's "Equipos" collection
 * @method Tarea               setTareaEquipo()            Sets the current record's "TareaEquipo" collection
 * @method Tarea               setRadioportatiles()        Sets the current record's "Radioportatiles" collection
 * @method Tarea               setTareaRadioportatiles()   Sets the current record's "TareaRadioportatiles" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarea');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('franja_horaria', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Mañana',
              1 => 'Tarde',
              2 => 'Mañana y Tarde',
              3 => 'Noche',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('lugar_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('evento_id', '', null);
        $this->hasColumn('voluntario_id', '', null);
        $this->hasColumn('perfil_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('voluntarios_necesarios', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('estado', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Sin asignar',
              1 => 'Incompleta',
              2 => 'Asignada',
             ),
             'notnull' => true,
             'default' => 'Sin asignar',
             ));
        $this->hasColumn('departamento_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('hora_comienzo', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('hora_fin', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Voluntario', array(
             'local' => 'voluntario_id',
             'foreign' => 'id'));

        $this->hasOne('Evento', array(
             'local' => 'evento_id',
             'foreign' => 'id'));

        $this->hasOne('Lugar', array(
             'local' => 'lugar_id',
             'foreign' => 'id'));

        $this->hasOne('Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $this->hasOne('Departamento', array(
             'local' => 'departamento_id',
             'foreign' => 'id'));

        $this->hasMany('Equipo as Equipos', array(
             'refClass' => 'TareaEquipo',
             'local' => 'tarea_id',
             'foreign' => 'equipo_id'));

        $this->hasMany('TareaEquipo', array(
             'local' => 'id',
             'foreign' => 'tarea_id'));

        $this->hasMany('Radioportatil as Radioportatiles', array(
             'refClass' => 'TareaRadioportatil',
             'local' => 'tarea_id',
             'foreign' => 'radioportatil_id'));

        $this->hasMany('TareaRadioportatil as TareaRadioportatiles', array(
             'local' => 'id',
             'foreign' => 'tarea_id'));
    }
}