<?php

/**
 * BaseMovimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property boolean $grande
 * @property Doctrine_Collection $Voluntario
 * 
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method boolean             getGrande()     Returns the current record's "grande" value
 * @method Doctrine_Collection getVoluntario() Returns the current record's "Voluntario" collection
 * @method Movimiento          setNombre()     Sets the current record's "nombre" value
 * @method Movimiento          setGrande()     Sets the current record's "grande" value
 * @method Movimiento          setVoluntario() Sets the current record's "Voluntario" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMovimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('movimiento');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('grande', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Voluntario', array(
             'local' => 'id',
             'foreign' => 'movimiento_id'));
    }
}