<?php

/**
 * BaseTareaEquipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tarea_id
 * @property integer $equipo_id
 * @property Tarea $Tareas
 * @property Equipo $Equipo
 * 
 * @method integer     getTareaId()   Returns the current record's "tarea_id" value
 * @method integer     getEquipoId()  Returns the current record's "equipo_id" value
 * @method Tarea       getTareas()    Returns the current record's "Tareas" value
 * @method Equipo      getEquipos()   Returns the current record's "Equipos" value
 * @method Tarea       getTarea()     Returns the current record's "Tarea" value
 * @method Equipo      getEquipo()    Returns the current record's "Equipo" value
 * @method TareaEquipo setTareaId()   Sets the current record's "tarea_id" value
 * @method TareaEquipo setEquipoId()  Sets the current record's "equipo_id" value
 * @method TareaEquipo setTareas()    Sets the current record's "Tareas" value
 * @method TareaEquipo setEquipos()   Sets the current record's "Equipos" value
 * @method TareaEquipo setTarea()     Sets the current record's "Tarea" value
 * @method TareaEquipo setEquipo()    Sets the current record's "Equipo" values
 * @property Tarea $Tarea
 * @property Equipo $Equipo
 * 
 * @method integer     getTareaId()   Returns the current record's "tarea_id" value
 * @method integer     getEquipoId()  Returns the current record's "equipo_id" value
 * @method Tarea       getTareas()    Returns the current record's "Tareas" value
 * @method Equipo      getEquipos()   Returns the current record's "Equipos" value
 * @method Tarea       getTarea()     Returns the current record's "Tarea" value
 * @method Equipo      getEquipo()    Returns the current record's "Equipo" value
 * @method TareaEquipo setTareaId()   Sets the current record's "tarea_id" value
 * @method TareaEquipo setEquipoId()  Sets the current record's "equipo_id" value
 * @method TareaEquipo setTareas()    Sets the current record's "Tareas" value
 * @method TareaEquipo setEquipos()   Sets the current record's "Equipos" value
 * @method TareaEquipo setTarea()     Sets the current record's "Tarea" value
 * @method TareaEquipo setEquipo()    Sets the current record's "Equipo" value
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTareaEquipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarea_equipo');
        $this->hasColumn('tarea_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('equipo_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tarea as Tareas', array(
             'local' => 'tarea_id',
             'foreign' => 'id'));

        $this->hasOne('Equipo as Equipos', array(
             'local' => 'equipo_id',
             'foreign' => 'id'));

        $this->hasOne('Tarea', array(
             'local' => 'tarea_id',
             'foreign' => 'id'));

        $this->hasOne('Equipo', array(
             'local' => 'equipo_id',
             'foreign' => 'id'));
    }
}