<?php

/**
 * BaseTurnoVoluntario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property  $turno_id
 * @property  $voluntario_id
 * @property Turno $Turno
 * @property Voluntario $Voluntario
 * 
 * @method Turno           getTurno()      Returns the current record's "Turno" value
 * @method Voluntario      getVoluntario() Returns the current record's "Voluntario" value
 * @method TurnoVoluntario setTurno()      Sets the current record's "Turno" value
 * @method TurnoVoluntario setVoluntario() Sets the current record's "Voluntario" value
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTurnoVoluntario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('turno_voluntario');
        $this->hasColumn('turno_id', '', null);
        $this->hasColumn('voluntario_id', '', null);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Turno', array(
             'local' => 'turno_id',
             'foreign' => 'id'));

        $this->hasOne('Voluntario', array(
             'local' => 'voluntario_id',
             'foreign' => 'id'));
    }
}