<?php

/**
 * BasePerfilEquipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $perfil_id
 * @property integer $equipo_id
 * @property Perfil $Perfiles
 * @property Equipo $Equipo
 * 
 * @method integer      getPerfilId()  Returns the current record's "perfil_id" value
 * @method integer      getEquipoId()  Returns the current record's "equipo_id" value
 * @method Perfil       getPerfiles()  Returns the current record's "Perfiles" value
 * @method Equipo       getEquipos()   Returns the current record's "Equipos" value
 * @method Perfil       getPerfil()    Returns the current record's "Perfil" value
 * @method Equipo       getEquipo()    Returns the current record's "Equipo" value
 * @method PerfilEquipo setPerfilId()  Sets the current record's "perfil_id" value
 * @method PerfilEquipo setEquipoId()  Sets the current record's "equipo_id" value
 * @method PerfilEquipo setPerfiles()  Sets the current record's "Perfiles" value
 * @method PerfilEquipo setEquipos()   Sets the current record's "Equipos" value
 * @method PerfilEquipo setPerfil()    Sets the current record's "Perfil" value
 * @method PerfilEquipo setEquipo()    Sets the current record's "Equipo" values
 * @property Perfil $Perfil
 * @property Equipo $Equipo
 * 
 * @method integer      getPerfilId()  Returns the current record's "perfil_id" value
 * @method integer      getEquipoId()  Returns the current record's "equipo_id" value
 * @method Perfil       getPerfiles()  Returns the current record's "Perfiles" value
 * @method Equipo       getEquipos()   Returns the current record's "Equipos" value
 * @method Perfil       getPerfil()    Returns the current record's "Perfil" value
 * @method Equipo       getEquipo()    Returns the current record's "Equipo" value
 * @method PerfilEquipo setPerfilId()  Sets the current record's "perfil_id" value
 * @method PerfilEquipo setEquipoId()  Sets the current record's "equipo_id" value
 * @method PerfilEquipo setPerfiles()  Sets the current record's "Perfiles" value
 * @method PerfilEquipo setEquipos()   Sets the current record's "Equipos" value
 * @method PerfilEquipo setPerfil()    Sets the current record's "Perfil" value
 * @method PerfilEquipo setEquipo()    Sets the current record's "Equipo" value
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfilEquipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil_equipo');
        $this->hasColumn('perfil_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('equipo_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Perfil as Perfiles', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $this->hasOne('Equipo as Equipos', array(
             'local' => 'equipo_id',
             'foreign' => 'id'));

        $this->hasOne('Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $this->hasOne('Equipo', array(
             'local' => 'equipo_id',
             'foreign' => 'id'));
    }
}