<?php

/**
 * BasePerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Equipos
 * @property Doctrine_Collection $Tarea
 * @property Doctrine_Collection $PerfilEquipo
 * 
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getDescripcion()  Returns the current record's "descripcion" value
 * @method Doctrine_Collection getEquipos()      Returns the current record's "Equipos" collection
 * @method Doctrine_Collection getTarea()        Returns the current record's "Tarea" collection
 * @method Doctrine_Collection getPerfilEquipo() Returns the current record's "PerfilEquipo" collection
 * @method Perfil              setNombre()       Sets the current record's "nombre" value
 * @method Perfil              setDescripcion()  Sets the current record's "descripcion" value
 * @method Perfil              setEquipos()      Sets the current record's "Equipos" collection
 * @method Perfil              setTarea()        Sets the current record's "Tarea" collection
 * @method Perfil              setPerfilEquipo() Sets the current record's "PerfilEquipo" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Equipo as Equipos', array(
             'refClass' => 'PerfilEquipo',
             'local' => 'perfil_id',
             'foreign' => 'equipo_id'));

        $this->hasMany('Tarea', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));

        $this->hasMany('PerfilEquipo', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));
    }
}