<?php

/**
 * BaseEquipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $notas
 * @property boolean $bolsa
 * @property boolean $acreditable
 * @property Doctrine_Collection $Perfiles
 * @property Doctrine_Collection $Tareas
 * @property Doctrine_Collection $Voluntarios
 * @property Doctrine_Collection $TareaEquipo
 * @property Doctrine_Collection $PerfilEquipo
 * 
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getNotas()        Returns the current record's "notas" value
 * @method boolean             getBolsa()        Returns the current record's "bolsa" value
 * @method boolean             getAcreditable()  Returns the current record's "acreditable" value
 * @method Doctrine_Collection getPerfiles()     Returns the current record's "Perfiles" collection
 * @method Doctrine_Collection getTareas()       Returns the current record's "Tareas" collection
 * @method Doctrine_Collection getVoluntarios()  Returns the current record's "Voluntarios" collection
 * @method Doctrine_Collection getTareaEquipo()  Returns the current record's "TareaEquipo" collection
 * @method Doctrine_Collection getPerfilEquipo() Returns the current record's "PerfilEquipo" collection
 * @method Equipo              setNombre()       Sets the current record's "nombre" value
 * @method Equipo              setNotas()        Sets the current record's "notas" value
 * @method Equipo              setBolsa()        Sets the current record's "bolsa" value
 * @method Equipo              setAcreditable()  Sets the current record's "acreditable" value
 * @method Equipo              setPerfiles()     Sets the current record's "Perfiles" collection
 * @method Equipo              setTareas()       Sets the current record's "Tareas" collection
 * @method Equipo              setVoluntarios()  Sets the current record's "Voluntarios" collection
 * @method Equipo              setTareaEquipo()  Sets the current record's "TareaEquipo" collection
 * @method Equipo              setPerfilEquipo() Sets the current record's "PerfilEquipo" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipo');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('notas', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('bolsa', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('acreditable', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Perfil as Perfiles', array(
             'refClass' => 'PerfilEquipo',
             'local' => 'equipo_id',
             'foreign' => 'perfil_id'));

        $this->hasMany('Tarea as Tareas', array(
             'refClass' => 'TareaEquipo',
             'local' => 'equipo_id',
             'foreign' => 'tarea_id'));

        $this->hasMany('Voluntario as Voluntarios', array(
             'local' => 'id',
             'foreign' => 'equipo_id'));

        $this->hasMany('TareaEquipo', array(
             'local' => 'id',
             'foreign' => 'equipo_id'));

        $this->hasMany('PerfilEquipo', array(
             'local' => 'id',
             'foreign' => 'equipo_id'));
    }
}