<?php

/**
 * BaseTurno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property integer $lugar_id
 * @property date $fecha
 * @property time $hora_comienzo
 * @property time $hora_fin
 * @property Doctrine_Collection $Voluntarios
 * @property Lugar $Lugar
 * @property Doctrine_Collection $VoluntariosTurno
 * 
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getDescripcion()      Returns the current record's "descripcion" value
 * @method integer             getLugarId()          Returns the current record's "lugar_id" value
 * @method date                getFecha()            Returns the current record's "fecha" value
 * @method time                getHoraComienzo()     Returns the current record's "hora_comienzo" value
 * @method time                getHoraFin()          Returns the current record's "hora_fin" value
 * @method Doctrine_Collection getVoluntarios()      Returns the current record's "Voluntarios" collection
 * @method Lugar               getLugar()            Returns the current record's "Lugar" value
 * @method Doctrine_Collection getVoluntariosTurno() Returns the current record's "VoluntariosTurno" collection
 * @method Turno               setNombre()           Sets the current record's "nombre" value
 * @method Turno               setDescripcion()      Sets the current record's "descripcion" value
 * @method Turno               setLugarId()          Sets the current record's "lugar_id" value
 * @method Turno               setFecha()            Sets the current record's "fecha" value
 * @method Turno               setHoraComienzo()     Sets the current record's "hora_comienzo" value
 * @method Turno               setHoraFin()          Sets the current record's "hora_fin" value
 * @method Turno               setVoluntarios()      Sets the current record's "Voluntarios" collection
 * @method Turno               setLugar()            Sets the current record's "Lugar" value
 * @method Turno               setVoluntariosTurno() Sets the current record's "VoluntariosTurno" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTurno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('turno');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('lugar_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora_comienzo', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('hora_fin', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Voluntario as Voluntarios', array(
             'refClass' => 'TurnoVoluntario',
             'local' => 'turno_id',
             'foreign' => 'voluntario_id'));

        $this->hasOne('Lugar', array(
             'local' => 'lugar_id',
             'foreign' => 'id'));

        $this->hasMany('TurnoVoluntario as VoluntariosTurno', array(
             'local' => 'id',
             'foreign' => 'turno_id'));
    }
}