<?php

/**
 * BaseLugar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $arciprestazgo_id
 * @property string $mapa
 * @property string $municipio
 * @property string $direccion
 * @property string $telefono
 * @property string $metro_cercano
 * @property string $autobus_cercano
 * @property string $servicios_cercanos
 * @property string $descripcion
 * @property Arciprestazgo $Arciprestazgo
 * @property Doctrine_Collection $Evento
 * @property Doctrine_Collection $Tarea
 * @property Doctrine_Collection $Turno
 * 
 * @method string              getNombre()             Returns the current record's "nombre" value
 * @method integer             getArciprestazgoId()    Returns the current record's "arciprestazgo_id" value
 * @method string              getMapa()               Returns the current record's "mapa" value
 * @method string              getMunicipio()          Returns the current record's "municipio" value
 * @method string              getDireccion()          Returns the current record's "direccion" value
 * @method string              getTelefono()           Returns the current record's "telefono" value
 * @method string              getMetroCercano()       Returns the current record's "metro_cercano" value
 * @method string              getAutobusCercano()     Returns the current record's "autobus_cercano" value
 * @method string              getServiciosCercanos()  Returns the current record's "servicios_cercanos" value
 * @method string              getDescripcion()        Returns the current record's "descripcion" value
 * @method Arciprestazgo       getArciprestazgo()      Returns the current record's "Arciprestazgo" value
 * @method Doctrine_Collection getEvento()             Returns the current record's "Evento" collection
 * @method Doctrine_Collection getTarea()              Returns the current record's "Tarea" collection
 * @method Doctrine_Collection getTurno()              Returns the current record's "Turno" collection
 * @method Lugar               setNombre()             Sets the current record's "nombre" value
 * @method Lugar               setArciprestazgoId()    Sets the current record's "arciprestazgo_id" value
 * @method Lugar               setMapa()               Sets the current record's "mapa" value
 * @method Lugar               setMunicipio()          Sets the current record's "municipio" value
 * @method Lugar               setDireccion()          Sets the current record's "direccion" value
 * @method Lugar               setTelefono()           Sets the current record's "telefono" value
 * @method Lugar               setMetroCercano()       Sets the current record's "metro_cercano" value
 * @method Lugar               setAutobusCercano()     Sets the current record's "autobus_cercano" value
 * @method Lugar               setServiciosCercanos()  Sets the current record's "servicios_cercanos" value
 * @method Lugar               setDescripcion()        Sets the current record's "descripcion" value
 * @method Lugar               setArciprestazgo()      Sets the current record's "Arciprestazgo" value
 * @method Lugar               setEvento()             Sets the current record's "Evento" collection
 * @method Lugar               setTarea()              Sets the current record's "Tarea" collection
 * @method Lugar               setTurno()              Sets the current record's "Turno" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLugar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lugar');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('arciprestazgo_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('mapa', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('municipio', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('direccion', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('metro_cercano', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('autobus_cercano', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('servicios_cercanos', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Arciprestazgo', array(
             'local' => 'arciprestazgo_id',
             'foreign' => 'id'));

        $this->hasMany('Evento', array(
             'local' => 'id',
             'foreign' => 'lugar_id'));

        $this->hasMany('Tarea', array(
             'local' => 'id',
             'foreign' => 'lugar_id'));

        $this->hasMany('Turno', array(
             'local' => 'id',
             'foreign' => 'lugar_id'));
    }
}