<?php

/**
 * BaseVicaria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $diocesis_id
 * @property Diocesis $Diocesis
 * @property Doctrine_Collection $Arciprestazgo
 * 
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method integer             getDiocesisId()    Returns the current record's "diocesis_id" value
 * @method Diocesis            getDiocesis()      Returns the current record's "Diocesis" value
 * @method Doctrine_Collection getArciprestazgo() Returns the current record's "Arciprestazgo" collection
 * @method Vicaria             setNombre()        Sets the current record's "nombre" value
 * @method Vicaria             setDiocesisId()    Sets the current record's "diocesis_id" value
 * @method Vicaria             setDiocesis()      Sets the current record's "Diocesis" value
 * @method Vicaria             setArciprestazgo() Sets the current record's "Arciprestazgo" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVicaria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vicaria');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('diocesis_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Diocesis', array(
             'local' => 'diocesis_id',
             'foreign' => 'id'));

        $this->hasMany('Arciprestazgo', array(
             'local' => 'id',
             'foreign' => 'vicaria_id'));
    }
}