<?php

/**
 * BaseRadioportatil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $numero_serie
 * @property Doctrine_Collection $Tareas
 * @property Doctrine_Collection $RadioportatilTareas
 * 
 * @method string              getNumeroSerie()         Returns the current record's "numero_serie" value
 * @method Doctrine_Collection getTareas()              Returns the current record's "Tareas" collection
 * @method Doctrine_Collection getRadioportatilTareas() Returns the current record's "RadioportatilTareas" collection
 * @method Radioportatil       setNumeroSerie()         Sets the current record's "numero_serie" value
 * @method Radioportatil       setTareas()              Sets the current record's "Tareas" collection
 * @method Radioportatil       setRadioportatilTareas() Sets the current record's "RadioportatilTareas" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadioportatil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radioportatil');
        $this->hasColumn('numero_serie', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarea as Tareas', array(
             'refClass' => 'TareaRadioportatil',
             'local' => 'radioportatil_id',
             'foreign' => 'tarea_id'));

        $this->hasMany('TareaRadioportatil as RadioportatilTareas', array(
             'local' => 'id',
             'foreign' => 'radioportatil_id'));
    }
}