<?php

/**
 * BaseArciprestazgo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $diocesis_id
 * @property integer $vicaria_id
 * @property Diocesis $Diocesis
 * @property Vicaria $Vicaria
 * @property Doctrine_Collection $Parroquia
 * @property Doctrine_Collection $Lugar
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method integer             getDiocesisId()  Returns the current record's "diocesis_id" value
 * @method integer             getVicariaId()   Returns the current record's "vicaria_id" value
 * @method Diocesis            getDiocesis()    Returns the current record's "Diocesis" value
 * @method Vicaria             getVicaria()     Returns the current record's "Vicaria" value
 * @method Doctrine_Collection getParroquia()   Returns the current record's "Parroquia" collection
 * @method Doctrine_Collection getLugar()       Returns the current record's "Lugar" collection
 * @method Arciprestazgo       setNombre()      Sets the current record's "nombre" value
 * @method Arciprestazgo       setDiocesisId()  Sets the current record's "diocesis_id" value
 * @method Arciprestazgo       setVicariaId()   Sets the current record's "vicaria_id" value
 * @method Arciprestazgo       setDiocesis()    Sets the current record's "Diocesis" value
 * @method Arciprestazgo       setVicaria()     Sets the current record's "Vicaria" value
 * @method Arciprestazgo       setParroquia()   Sets the current record's "Parroquia" collection
 * @method Arciprestazgo       setLugar()       Sets the current record's "Lugar" collection
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArciprestazgo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('arciprestazgo');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('diocesis_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('vicaria_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Diocesis', array(
             'local' => 'diocesis_id',
             'foreign' => 'id'));

        $this->hasOne('Vicaria', array(
             'local' => 'vicaria_id',
             'foreign' => 'id'));

        $this->hasMany('Parroquia', array(
             'local' => 'id',
             'foreign' => 'arciprestazgo_id'));

        $this->hasMany('Lugar', array(
             'local' => 'id',
             'foreign' => 'arciprestazgo_id'));
    }
}