# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: single_address
      delivery_address: mzaforas@gmail.com

dev:

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  mailer:
    class: sfMailer
    param:
      delivery_strategy: spool
      spool_class:       Swift_FileSpool
      spool_arguments:   [/home/jmjadmin/voluntariosjmj_mail/]
#      spool_arguments:   [/kunden/homepages/5/d312877031/htdocs/voluntariosjmj_mail/]
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      # delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host: smtp.jmj2011madrid.com
          port: 25
          encryption: ~
          username: voluntarios.jmj2011madrid.com
          password: inf09p055
