<?php

/**
 * EquipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Equipo');
    }

    /* Obsoleto to delete */
    public static function coincideFranjaHoraria($franja_1, $franja_2)
    {
      if ($franja_1 == $franja_2) {
    	return true;
      }

      if ($franja_1 == "Mañana y Tarde" and ($franja_2 == "Mañana" or $franja_2 == "Tarde")) {
    	return true;
      }

      if ($franja_2 == "Mañana y Tarde" and ($franja_1 == "Mañana" or $franja_1 == "Tarde")) {
    	return true;
      }

      return false;
    }

    /**
     * Devuelve true si el equipo esta libre para dicha fecha y franaja.
     * Como opción se le puede pasar una tarea, la cual no será tenida en
     * cuenta a la hora de comprabar la disponibilidad (Caso de editar una
     * Tarea que tiene asignados equipos)
     *
    public static function isEquipoDisponible($equipo, $fecha, $tarea_referencia=null)
    {
      foreach($equipo->getTareas() as $tarea) {
        if ($tarea_referencia and $tarea->getId() == $tarea_referencia->getId()) {
          echo "Ignorada -".$tarea->getId()."\n";
          continue;
        }
    	//if( $tarea->getFecha() == $fecha and EquipoTable::coincideFranjaHoraria($franja,$tarea->getFranjaHoraria()))
        //  return false;
    	// Cambio solicitado por Ana C.
        if($tarea->getFecha() == $fecha) {
          echo $tarea->getId()."\n";
          return false;
    	}
      }
      //die("AAAA");
      return true;
    }*/

    public static function getDisponibles($tarea)
    {
      $fecha = $tarea->getFecha();
      $perfil_id = $tarea->getPerfilId();

      if ($perfil_id) {
	$q = Doctrine_Query::create()->from('Equipo e')
	  ->leftJoin('e.Tareas t')
	  ->leftJoin('e.Perfiles p')
	  ->leftJoin('e.Voluntarios v')
	  ->andWhere('e.acreditable = 1')
	  ->andWhere('p.id = '.$perfil_id);
      } else {
	$q = Doctrine_Query::create()->from('Equipo e')
	  ->leftJoin('e.Tareas t')
	  ->leftJoin('e.Perfiles p')
	  ->leftJoin('e.Voluntarios v')
	  ->andWhere('e.acreditable = 1');
      }

      $equipos = $q->execute();
      $equipos_disponibles = array();
      foreach ($equipos as $equipo) {
	if($equipo->estaDisponible($fecha, $tarea->getFranjaHoraria())){
	  $equipos_disponibles[] = $equipo;
	}
      }

      return $equipos_disponibles;
    }
}