<?php

/**
 * LugarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LugarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LugarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lugar');
    }
    
    public static function retrieveBackendLugarList(Doctrine_Query $q) {
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias.'.Arciprestazgo arciprestazgo')
	->leftJoin('arciprestazgo.Vicaria vicaria')
	->leftJoin('vicaria.Diocesis diocesis');
      return $q;
    }
}