<?php

/**
 * Movimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Movimiento extends BaseMovimiento
{
  public function __toString() {
    return $this->getId() ? $this->getNombre() : '';
  }
}
