<?php

/**
 * Parroquia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Parroquia extends BaseParroquia
{
  public function __toString() {
    if ($this->getNombre()) {
      return $this->getNombre().' ('.$this->getMunicipio().')';
    } else {
      return '';
    }
  }

  public function getDiocesis() {
    return $this->getArciprestazgo()->getVicaria()->getDiocesis();
  }

  public function getVicaria() {
    return $this->getArciprestazgo()->getVicaria();
  }

}
