<?php

/**
 * RadioportatilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadioportatilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadioportatilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radioportatil');
    }

    public static function disponibles($tarea)
    {
      $fecha = $tarea->getFecha();
      $hora_comienzo = $tarea->getHoraComienzo();
      $hora_fin = $tarea->getHoraFin();

      if (!$fecha || !$hora_comienzo || !$hora_fin) {
	return array();
      }

      $connection = Doctrine_Manager::getInstance()->getCurrentConnection();
      return $connection->fetchAssoc('
      SELECT * FROM radioportatil WHERE id NOT IN
        (SELECT tr.radioportatil_id FROM tarea_radioportatil tr
           LEFT JOIN tarea t ON t.id = tr.tarea_id
           WHERE (t.fecha != '.$fecha.') OR 
                 (t.fecha = '.$fecha.' AND (t.hora_comienzo >= "'.$hora_fin.'"  OR t.hora_fin <= "'.$hora_comienzo.'")))');
    }

    public static function asignados($tarea)
    {
      return Doctrine_Query::create()
      ->from('Radioportatil r')
      ->leftJoin('r.RadioportatilTareas rt')
      ->leftJoin('rt.Tarea t')
      ->where('t.id = '.$tarea->getId())
      ->execute();
    }
    
}