<?php

/**
 * TareaEquipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TareaEquipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TareaEquipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TareaEquipo');
    }
}