<?php

/**
 * Tarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    voluntarios
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tarea extends BaseTarea
{
  public function __toString() {
    return $this->getId() ? $this->getNombre() : '';
  }

  /**
   * Número de equipos asignados a la tarea
   */
  public function getNumeroEquipos() {
    return $this->getEquipos()->count();
  }

  /**
   * Número de equipos asignados a la tarea
   */
  public function getNumeroRadioportatiles() {
    return $this->getRadioportatiles()->count();
  }

  /**
   *
   */
  public function getNumeroVoluntarios() {
    $q = Doctrine_Query::create()
      ->from('Voluntario v')
      ->select('COUNT(id)')
      ->leftJoin('v.Equipo e')
      ->leftJoin('e.TareaEquipo te')
      ->where('te.tarea_id = '.$this->getId());
    return $q->fetchOne()->get('COUNT');
  }

  /**
   *
   */
  public function getVoluntarios() {
    $q = Doctrine_Query::create()
      ->from('Voluntario v')
      ->leftJoin('v.Equipo e')
      ->leftJoin('e.TareaEquipo te')
      ->where('te.tarea_id = '.$this->getId());
    return $q->execute();
  }

  /**
   * Actualizamos el estado de la tarea en función de los voluntarios asignados y los necesarios
   */
  public function actualizarEstado() {
    $voluntarios_necesarios = $this->getVoluntariosNecesarios();
    $voluntarios_asignados = $this->getNumeroVoluntarios();

    if ($voluntarios_asignados == 0) {
      $this->setEstado('Sin asignar');
      $this->save();
      return;
    } elseif ($voluntarios_necesarios > $voluntarios_asignados) {
      $this->setEstado('Incompleta');
      $this->save();
      return;
    } elseif ($voluntarios_necesarios <= $voluntarios_asignados) {
      $this->setEstado('Asignada');
      $this->save();
      return;
    }
  }

}
