<?php

/**
 * TareaRadioportatilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TareaRadioportatilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TareaRadioportatilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TareaRadioportatil');
    }
}