<?php

/**
 * TurnoVoluntarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TurnoVoluntarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TurnoVoluntarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TurnoVoluntario');
    }
}