<?php

/**
 * VicariaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VicariaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VicariaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vicaria');
    }
}