generator:
  class: sfDoctrineGenerator
  param:
    model_class:           evento
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          evento
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        descripcion: {label: Descripción}
      list:    
        title: Listado de eventos
        display: [=nombre, descripcion, lugar, comienzo, fin]
        batch_actions:   {}
        object_actions: {}
        
      filter:  ~
      form:    ~
      edit:
        title: Editar evento
      new:
        title: Nuevo evento
