generator:
  class: sfDoctrineGenerator
  param:
    model_class:           movimiento
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          movimiento
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        grande: {label: Es grande}
      list:
        title: Listado de movimientos
        display: [nombre, grande]
        object_actions: {}
        actions: {}
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:
        title: Editar departamento
      new:
        title: Nuevo departamento
