generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tarea
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tarea
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        voluntario: {label: Responsable}
        voluntario_id: {label: Responsable}
        descripcion: {label: Descripción}
        numero_equipos: {label: Equipos asignados}
        numero_voluntarios: {label: Voluntarios}
        fecha: {date_format: dd/MM/yyyy}
        equipos_list: {label: Equipos}
      list:    
        title: Listado de tareas
        display: [id, nombre, departamento, fecha, franja_horaria, evento, lugar, estado, _numero_voluntarios]
        object_actions:  { _edit: ~, ficha: ~}
        batch_actions: {}
        table_method: retrieveBackendTareaList 
        max_per_page: 15
      filter:  
        display: [id, nombre, departamento_id, fecha, franja_horaria, evento_id, lugar_id, descripcion, voluntario_id, perfil_id, equipos_list, estado]
      form: ~
      edit:
        title: Editar tarea
        actions: {_list: ~, ficha: ~, _save: ~}
      new:
        title: Nueva tarea

