generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tarea
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tarea
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        descripcion: {label: Descripción}
        numero_equipos: {label: Equipos asignados}
        numero_voluntarios: {label: Voluntarios asignados}
        fecha: {date_format: dd/MM/yyyy}
        numero_radioportatiles: { label: Radioportátiles}
      list:    
        title: Listado de tareas
        display: [=id, nombre, departamento, fecha, franja_horaria, evento, lugar, numero_radioportatiles]
        object_actions:  { _edit: ~, ficha: ~}
        batch_actions: {}
        table_method: retrieveBackendTareaList 
        max_per_page: 40
      filter:  
        display: ~
      form:
        display: [nombre, departamento_id, fecha, franja_horaria, hora_comienzo, hora_fin, evento_id, lugar_id, descripcion, voluntario_id, perfil_id]
      edit:
        title: Editar tarea
        actions: {_list: ~, ficha: ~, _save: ~}
      new:
        title: Nueva tarea
